# Conda Environment File
#
# Reference:
#   https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html
#
name: openafpm-cad-core
channels:
  - conda-forge
dependencies:
  - freecad==0.19.2
  - sphinx==4.1.1
  - sphinx_rtd_theme==0.5.2
  - python>=3.8
  - pip
  - pip:
    - freecad-to-obj==0.1.0
